# coding: utf-8

"""
    CodeChef API

    CodeChef API to support different applications.  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import codechef_client
from codechef_client.api.users_api import UsersApi  # noqa: E501
from codechef_client.rest import ApiException


class TestUsersApi(unittest.TestCase):
    """UsersApi unit test stubs"""

    def setUp(self):
        self.api = codechef_client.api.users_api.UsersApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_users_get(self):
        """Test case for users_get

        Get the list of users maximum 20.  # noqa: E501
        """
        pass

    def test_users_me_get(self):
        """Test case for users_me_get

        Fetches all the details of logged-in user.  # noqa: E501
        """
        pass

    def test_users_username_get(self):
        """Test case for users_username_get

        Fetches all the details of a user.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
