# coding: utf-8

"""
    CodeChef API

    CodeChef API to support different applications.  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import codechef_client
from codechef_client.api.todo_api import TodoApi  # noqa: E501
from codechef_client.rest import ApiException


class TestTodoApi(unittest.TestCase):
    """TodoApi unit test stubs"""

    def setUp(self):
        self.api = codechef_client.api.todo_api.TodoApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_todo_add_post(self):
        """Test case for todo_add_post

        Adds a problem to todo list.  # noqa: E501
        """
        pass

    def test_todo_delete_all_delete(self):
        """Test case for todo_delete_all_delete

        Deletes all the problems added to the todo list.  # noqa: E501
        """
        pass

    def test_todo_delete_delete(self):
        """Test case for todo_delete_delete

        Deletes a problem added to the todo list.  # noqa: E501
        """
        pass

    def test_todo_problems_get(self):
        """Test case for todo_problems_get

        Gets problems listed in todo.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
