# coding: utf-8

"""
    CodeChef API

    CodeChef API to support different applications.  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import codechef_client
from codechef_client.api.ide_api import IDEApi  # noqa: E501
from codechef_client.rest import ApiException


class TestIDEApi(unittest.TestCase):
    """IDEApi unit test stubs"""

    def setUp(self):
        self.api = codechef_client.api.ide_api.IDEApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_ide_run_post(self):
        """Test case for ide_run_post

        Runs a code submitted by user.  # noqa: E501
        """
        pass

    def test_ide_status_get(self):
        """Test case for ide_status_get

        Get status of submitted code.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
