# coding: utf-8

"""
    CodeChef API

    CodeChef API to support different applications.  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import codechef_client
from codechef_client.api.contests_api import ContestsApi  # noqa: E501
from codechef_client.rest import ApiException


class TestContestsApi(unittest.TestCase):
    """ContestsApi unit test stubs"""

    def setUp(self):
        self.api = codechef_client.api.contests_api.ContestsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_contests_contest_code_get(self):
        """Test case for contests_contest_code_get

        Get contest details.  # noqa: E501
        """
        pass

    def test_contests_get(self):
        """Test case for contests_get

        Get the list of contests.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
