# coding: utf-8

"""
    CodeChef API

    CodeChef API to support different applications.  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import codechef_client
from codechef_client.api.problems_api import ProblemsApi  # noqa: E501
from codechef_client.rest import ApiException


class TestProblemsApi(unittest.TestCase):
    """ProblemsApi unit test stubs"""

    def setUp(self):
        self.api = codechef_client.api.problems_api.ProblemsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_problems_category_name_get(self):
        """Test case for problems_category_name_get

        Get the list of problems for given categoryName.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
