# coding: utf-8

"""
    CodeChef API

    CodeChef API to support different applications.  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import codechef_client
from codechef_client.api.rankings_api import RankingsApi  # noqa: E501
from codechef_client.rest import ApiException


class TestRankingsApi(unittest.TestCase):
    """RankingsApi unit test stubs"""

    def setUp(self):
        self.api = codechef_client.api.rankings_api.RankingsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_rankings_contest_code_get(self):
        """Test case for rankings_contest_code_get

        Return ranklist for a particular contest.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
