# coding: utf-8

"""
    CodeChef API

    CodeChef API to support different applications.  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import codechef_client
from codechef_client.api.contest_problems_api import ContestProblemsApi  # noqa: E501
from codechef_client.rest import ApiException


class TestContestProblemsApi(unittest.TestCase):
    """ContestProblemsApi unit test stubs"""

    def setUp(self):
        self.api = codechef_client.api.contest_problems_api.ContestProblemsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_contests_contest_code_problems_problem_code_get(self):
        """Test case for contests_contest_code_problems_problem_code_get

        Get details of a problem.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
