# coding: utf-8

"""
    CodeChef API

    CodeChef API to support different applications.  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import codechef_client
from codechef_client.models.inline_response_200_21 import InlineResponse20021  # noqa: E501
from codechef_client.rest import ApiException


class TestInlineResponse20021(unittest.TestCase):
    """InlineResponse20021 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse20021(self):
        """Test InlineResponse20021"""
        # FIXME: construct object with mandatory attributes with example values
        # model = codechef_client.models.inline_response_200_21.InlineResponse20021()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
