# coding: utf-8

"""
    CodeChef API

    CodeChef API to support different applications.  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import codechef_client
from codechef_client.api.tags_api import TagsApi  # noqa: E501
from codechef_client.rest import ApiException


class TestTagsApi(unittest.TestCase):
    """TagsApi unit test stubs"""

    def setUp(self):
        self.api = codechef_client.api.tags_api.TagsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_tags_problems_get(self):
        """Test case for tags_problems_get

        Get list of tags for a given problem.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
