# coding: utf-8

"""
    CodeChef API

    CodeChef API to support different applications.  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import codechef_client
from codechef_client.models.inline_response_200_19 import InlineResponse20019  # noqa: E501
from codechef_client.rest import ApiException


class TestInlineResponse20019(unittest.TestCase):
    """InlineResponse20019 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse20019(self):
        """Test InlineResponse20019"""
        # FIXME: construct object with mandatory attributes with example values
        # model = codechef_client.models.inline_response_200_19.InlineResponse20019()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
