# coding: utf-8

"""
    CodeChef API

    CodeChef API to support different applications.  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import codechef_client
from codechef_client.api.sets_api import SetsApi  # noqa: E501
from codechef_client.rest import ApiException


class TestSetsApi(unittest.TestCase):
    """SetsApi unit test stubs"""

    def setUp(self):
        self.api = codechef_client.api.sets_api.SetsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_sets_add_post(self):
        """Test case for sets_add_post

        Adds set to the user's account to whom the access token being used belongs.  # noqa: E501
        """
        pass

    def test_sets_delete_delete(self):
        """Test case for sets_delete_delete

        Deletes set from the user's account to whom the access token belongs.  # noqa: E501
        """
        pass

    def test_sets_get(self):
        """Test case for sets_get

        Get set details for logged in user  # noqa: E501
        """
        pass

    def test_sets_members_add_post(self):
        """Test case for sets_members_add_post

        Adds set members to an existing set of the user to whom the access token belongs.  # noqa: E501
        """
        pass

    def test_sets_members_delete_delete(self):
        """Test case for sets_members_delete_delete

        Removes members belonging to a set.  # noqa: E501
        """
        pass

    def test_sets_members_get_get(self):
        """Test case for sets_members_get_get

        Get set details for particular sets of the logged in user  # noqa: E501
        """
        pass

    def test_sets_update_put(self):
        """Test case for sets_update_put

        Updates set of the logged in user's account.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
