# coding: utf-8

"""
    CodeChef API

    CodeChef API to support different applications.  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import codechef_client
from codechef_client.models.add_set_member_parameters import AddSetMemberParameters  # noqa: E501
from codechef_client.rest import ApiException


class TestAddSetMemberParameters(unittest.TestCase):
    """AddSetMemberParameters unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAddSetMemberParameters(self):
        """Test AddSetMemberParameters"""
        # FIXME: construct object with mandatory attributes with example values
        # model = codechef_client.models.add_set_member_parameters.AddSetMemberParameters()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
