# coding: utf-8

"""
    CodeChef API

    CodeChef API to support different applications.  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import codechef_client
from codechef_client.models.state import State  # noqa: E501
from codechef_client.rest import ApiException


class TestState(unittest.TestCase):
    """State unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testState(self):
        """Test State"""
        # FIXME: construct object with mandatory attributes with example values
        # model = codechef_client.models.state.State()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
