# coding: utf-8

"""
    CodeChef API

    CodeChef API to support different applications.  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import codechef_client
from codechef_client.models.ide_status import IDEStatus  # noqa: E501
from codechef_client.rest import ApiException


class TestIDEStatus(unittest.TestCase):
    """IDEStatus unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testIDEStatus(self):
        """Test IDEStatus"""
        # FIXME: construct object with mandatory attributes with example values
        # model = codechef_client.models.ide_status.IDEStatus()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
