# coding: utf-8

"""
    CodeChef API

    CodeChef API to support different applications.  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import codechef_client
from codechef_client.models.contest_problems_list import ContestProblemsList  # noqa: E501
from codechef_client.rest import ApiException


class TestContestProblemsList(unittest.TestCase):
    """ContestProblemsList unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testContestProblemsList(self):
        """Test ContestProblemsList"""
        # FIXME: construct object with mandatory attributes with example values
        # model = codechef_client.models.contest_problems_list.ContestProblemsList()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
