# coding: utf-8

"""
    CodeChef API

    CodeChef API to support different applications.  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class AddSetMemberParameters(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'set_name': 'str',
        'member_handle': 'str'
    }

    attribute_map = {
        'set_name': 'setName',
        'member_handle': 'memberHandle'
    }

    def __init__(self, set_name=None, member_handle=None):  # noqa: E501
        """AddSetMemberParameters - a model defined in Swagger"""  # noqa: E501

        self._set_name = None
        self._member_handle = None
        self.discriminator = None

        if set_name is not None:
            self.set_name = set_name
        if member_handle is not None:
            self.member_handle = member_handle

    @property
    def set_name(self):
        """Gets the set_name of this AddSetMemberParameters.  # noqa: E501

        Enter the set name in the form of a string.  # noqa: E501

        :return: The set_name of this AddSetMemberParameters.  # noqa: E501
        :rtype: str
        """
        return self._set_name

    @set_name.setter
    def set_name(self, set_name):
        """Sets the set_name of this AddSetMemberParameters.

        Enter the set name in the form of a string.  # noqa: E501

        :param set_name: The set_name of this AddSetMemberParameters.  # noqa: E501
        :type: str
        """

        self._set_name = set_name

    @property
    def member_handle(self):
        """Gets the member_handle of this AddSetMemberParameters.  # noqa: E501

        Enter the username in the form of a string.  # noqa: E501

        :return: The member_handle of this AddSetMemberParameters.  # noqa: E501
        :rtype: str
        """
        return self._member_handle

    @member_handle.setter
    def member_handle(self, member_handle):
        """Sets the member_handle of this AddSetMemberParameters.

        Enter the username in the form of a string.  # noqa: E501

        :param member_handle: The member_handle of this AddSetMemberParameters.  # noqa: E501
        :type: str
        """

        self._member_handle = member_handle

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, AddSetMemberParameters):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
