# coding: utf-8

"""
    CodeChef API

    CodeChef API to support different applications.  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class ContestList(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'code': 'str',
        'name': 'str',
        'start_date': 'str',
        'end_date': 'str',
        'freezing_time': 'str'
    }

    attribute_map = {
        'code': 'code',
        'name': 'name',
        'start_date': 'startDate',
        'end_date': 'endDate',
        'freezing_time': 'freezingTime'
    }

    def __init__(self, code=None, name=None, start_date=None, end_date=None, freezing_time=None):  # noqa: E501
        """ContestList - a model defined in Swagger"""  # noqa: E501

        self._code = None
        self._name = None
        self._start_date = None
        self._end_date = None
        self._freezing_time = None
        self.discriminator = None

        if code is not None:
            self.code = code
        if name is not None:
            self.name = name
        if start_date is not None:
            self.start_date = start_date
        if end_date is not None:
            self.end_date = end_date
        if freezing_time is not None:
            self.freezing_time = freezing_time

    @property
    def code(self):
        """Gets the code of this ContestList.  # noqa: E501

        Contest code  # noqa: E501

        :return: The code of this ContestList.  # noqa: E501
        :rtype: str
        """
        return self._code

    @code.setter
    def code(self, code):
        """Sets the code of this ContestList.

        Contest code  # noqa: E501

        :param code: The code of this ContestList.  # noqa: E501
        :type: str
        """

        self._code = code

    @property
    def name(self):
        """Gets the name of this ContestList.  # noqa: E501

        Contest title/name  # noqa: E501

        :return: The name of this ContestList.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this ContestList.

        Contest title/name  # noqa: E501

        :param name: The name of this ContestList.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def start_date(self):
        """Gets the start_date of this ContestList.  # noqa: E501

        Start time of the contest  # noqa: E501

        :return: The start_date of this ContestList.  # noqa: E501
        :rtype: str
        """
        return self._start_date

    @start_date.setter
    def start_date(self, start_date):
        """Sets the start_date of this ContestList.

        Start time of the contest  # noqa: E501

        :param start_date: The start_date of this ContestList.  # noqa: E501
        :type: str
        """

        self._start_date = start_date

    @property
    def end_date(self):
        """Gets the end_date of this ContestList.  # noqa: E501

        End time of the contest  # noqa: E501

        :return: The end_date of this ContestList.  # noqa: E501
        :rtype: str
        """
        return self._end_date

    @end_date.setter
    def end_date(self, end_date):
        """Sets the end_date of this ContestList.

        End time of the contest  # noqa: E501

        :param end_date: The end_date of this ContestList.  # noqa: E501
        :type: str
        """

        self._end_date = end_date

    @property
    def freezing_time(self):
        """Gets the freezing_time of this ContestList.  # noqa: E501

        Freezing time of the contest  # noqa: E501

        :return: The freezing_time of this ContestList.  # noqa: E501
        :rtype: str
        """
        return self._freezing_time

    @freezing_time.setter
    def freezing_time(self, freezing_time):
        """Sets the freezing_time of this ContestList.

        Freezing time of the contest  # noqa: E501

        :param freezing_time: The freezing_time of this ContestList.  # noqa: E501
        :type: str
        """

        self._freezing_time = freezing_time

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ContestList):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
