# coding: utf-8

"""
    CodeChef API

    CodeChef API to support different applications.  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class IDERun(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'link': 'str',
        'status': 'str'
    }

    attribute_map = {
        'link': 'link',
        'status': 'status'
    }

    def __init__(self, link=None, status=None):  # noqa: E501
        """IDERun - a model defined in Swagger"""  # noqa: E501

        self._link = None
        self._status = None
        self.discriminator = None

        if link is not None:
            self.link = link
        if status is not None:
            self.status = status

    @property
    def link(self):
        """Gets the link of this IDERun.  # noqa: E501

        Link using which you can find other details for this submission.  # noqa: E501

        :return: The link of this IDERun.  # noqa: E501
        :rtype: str
        """
        return self._link

    @link.setter
    def link(self, link):
        """Sets the link of this IDERun.

        Link using which you can find other details for this submission.  # noqa: E501

        :param link: The link of this IDERun.  # noqa: E501
        :type: str
        """

        self._link = link

    @property
    def status(self):
        """Gets the status of this IDERun.  # noqa: E501

        Status of the code execution.  # noqa: E501

        :return: The status of this IDERun.  # noqa: E501
        :rtype: str
        """
        return self._status

    @status.setter
    def status(self, status):
        """Sets the status of this IDERun.

        Status of the code execution.  # noqa: E501

        :param status: The status of this IDERun.  # noqa: E501
        :type: str
        """

        self._status = status

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, IDERun):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
