# coding: utf-8

"""
    CodeChef API

    CodeChef API to support different applications.  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class IdeRunSourceCode(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'source_code': 'str',
        'language': 'str',
        'input': 'str'
    }

    attribute_map = {
        'source_code': 'sourceCode',
        'language': 'language',
        'input': 'input'
    }

    def __init__(self, source_code=None, language=None, input=None):  # noqa: E501
        """IdeRunSourceCode - a model defined in Swagger"""  # noqa: E501

        self._source_code = None
        self._language = None
        self._input = None
        self.discriminator = None

        if source_code is not None:
            self.source_code = source_code
        if language is not None:
            self.language = language
        if input is not None:
            self.input = input

    @property
    def source_code(self):
        """Gets the source_code of this IdeRunSourceCode.  # noqa: E501

        Source code of submission.  # noqa: E501

        :return: The source_code of this IdeRunSourceCode.  # noqa: E501
        :rtype: str
        """
        return self._source_code

    @source_code.setter
    def source_code(self, source_code):
        """Sets the source_code of this IdeRunSourceCode.

        Source code of submission.  # noqa: E501

        :param source_code: The source_code of this IdeRunSourceCode.  # noqa: E501
        :type: str
        """

        self._source_code = source_code

    @property
    def language(self):
        """Gets the language of this IdeRunSourceCode.  # noqa: E501

        language of submission.  # noqa: E501

        :return: The language of this IdeRunSourceCode.  # noqa: E501
        :rtype: str
        """
        return self._language

    @language.setter
    def language(self, language):
        """Sets the language of this IdeRunSourceCode.

        language of submission.  # noqa: E501

        :param language: The language of this IdeRunSourceCode.  # noqa: E501
        :type: str
        """

        self._language = language

    @property
    def input(self):
        """Gets the input of this IdeRunSourceCode.  # noqa: E501

        input of submission.  # noqa: E501

        :return: The input of this IdeRunSourceCode.  # noqa: E501
        :rtype: str
        """
        return self._input

    @input.setter
    def input(self, input):
        """Sets the input of this IdeRunSourceCode.

        input of submission.  # noqa: E501

        :param input: The input of this IdeRunSourceCode.  # noqa: E501
        :type: str
        """

        self._input = input

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, IdeRunSourceCode):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
