# coding: utf-8

"""
    CodeChef API

    CodeChef API to support different applications.  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class Problems(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'catergory_name': 'int'
    }

    attribute_map = {
        'catergory_name': 'catergoryName'
    }

    def __init__(self, catergory_name=None):  # noqa: E501
        """Problems - a model defined in Swagger"""  # noqa: E501

        self._catergory_name = None
        self.discriminator = None

        if catergory_name is not None:
            self.catergory_name = catergory_name

    @property
    def catergory_name(self):
        """Gets the catergory_name of this Problems.  # noqa: E501

        Global rank  # noqa: E501

        :return: The catergory_name of this Problems.  # noqa: E501
        :rtype: int
        """
        return self._catergory_name

    @catergory_name.setter
    def catergory_name(self, catergory_name):
        """Sets the catergory_name of this Problems.

        Global rank  # noqa: E501

        :param catergory_name: The catergory_name of this Problems.  # noqa: E501
        :type: int
        """

        self._catergory_name = catergory_name

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Problems):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
